// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Infrastructure.Data;

#nullable disable

namespace server.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250621205850_initDb")]
    partial class initDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("server.Domain.Entities.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EnhancedAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Solved")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Total")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnhancedAnswer = "",
                            Image = "uploads/Test1.png",
                            Question = "Y-Axis: Average cheese consumption in kilograms\r\nX-Axis: Years (1980 to 2020)\r\nCountries Represented: England (blue), Scotland (red), Wales (yellow), Northern Ireland (green)\r\n\r\nDetails:\r\nEngland:\r\n\r\n1980: ~110 kg\r\n\r\nGradual decrease over time\r\n\r\n2020: ~85 kg\r\n\r\nScotland:\r\n\r\n1980: ~85 kg\r\n\r\nRose significantly to a peak of ~105 kg in 1990\r\n\r\nSteady decline afterward\r\n\r\n2020: ~58 kg\r\n\r\nWales:\r\n\r\n1980: ~45 kg\r\n\r\nGradual increase, peaking slightly above 75 kg by 2010\r\n\r\nSlight increase to 2020: ~76 kg\r\n\r\nNorthern Ireland:\r\n\r\n1980: ~10 kg\r\n\r\nContinuous increase over time\r\n\r\n2020: ~60 kg",
                            Solved = false,
                            Title = "Average Cheese Consumption (1980–2020)",
                            Total = "",
                            UserAnswer = ""
                        },
                        new
                        {
                            Id = 2,
                            EnhancedAnswer = "",
                            Image = "uploads/Test2.png",
                            Question = "X-Axis: Quantity in tonnes\r\nCategories:\r\n\r\nBlue bars: Rice Production\r\n\r\nRed bars: Rice Consumption\r\n\r\nCountries and Data (Production vs. Consumption in tonnes):\r\nHungary:\r\n\r\nProduction: 540 tonnes\r\n\r\nConsumption: 532 tonnes\r\n\r\nPhilippines:\r\n\r\nProduction: 410 tonnes\r\n\r\nConsumption: 387 tonnes\r\n\r\nIndia:\r\n\r\nProduction: 106 tonnes\r\n\r\nConsumption: 104 tonnes\r\n\r\nQatar:\r\n\r\nProduction: 94 tonnes\r\n\r\nConsumption: 86 tonnes\r\n\r\nTunisia:\r\n\r\nProduction: 87 tonnes\r\n\r\nConsumption: 70 tonnes\r\n\r\nPakistan:\r\n\r\nProduction: 62 tonnes\r\n\r\nConsumption: 50 tonnes\r\n\r\nVietnam:\r\n\r\nProduction: 56 tonnes\r\n\r\nConsumption: 46 tonnes\r\n\r\nZambia:\r\n\r\nProduction: 53 tonnes\r\n\r\nConsumption: 46 tonnes\r\n\r\nBangladesh:\r\n\r\nProduction: 53 tonnes\r\n\r\nConsumption: 58 tonnes\r\n\r\nSouth Korea:\r\n\r\nProduction: 49 tonnes\r\n\r\nConsumption: 45 tonnes",
                            Solved = false,
                            Title = "Rice Production and Consumption in 2020",
                            Total = "",
                            UserAnswer = ""
                        },
                        new
                        {
                            Id = 3,
                            EnhancedAnswer = "",
                            Image = "uploads/Test3.png",
                            Question = "Y-Axis: Percentage (%)\r\nX-Axis Categories:\r\n\r\nUnder 15 years old\r\n\r\n15–64 years\r\n\r\n65 years and older\r\nSeasons Represented:\r\n\r\nSpring (blue)\r\n\r\nSummer (green)\r\n\r\nAutumn (yellow)\r\n\r\nWinter (red)\r\n\r\nBreakdown by Age Group:\r\nUnder 15 years old:\r\n\r\nSpring: ~30%\r\n\r\nSummer: ~45%\r\n\r\nAutumn: ~12%\r\n\r\nWinter: ~12%\r\n\r\n15–64 years:\r\n\r\nSpring: ~32%\r\n\r\nSummer: ~36%\r\n\r\nAutumn: ~20%\r\n\r\nWinter: ~12%\r\n\r\n65 years and older:\r\n\r\nSpring: ~31%\r\n\r\nSummer: ~35%\r\n\r\nAutumn: ~27%\r\n\r\nWinter: ~7%",
                            Solved = false,
                            Title = "Chart 3: Favourite Season by Age Group in Portugal",
                            Total = "",
                            UserAnswer = ""
                        },
                        new
                        {
                            Id = 4,
                            EnhancedAnswer = "",
                            Image = "uploads/Test4.png",
                            Question = "Pie Chart – Revenue Sources and Their Percentages:\r\nBroadcasting Rights (Blue): 52% – This is the largest source of revenue for international football teams.\r\n\r\nMatch Day Revenue (Red): 15% – Represents the income from ticket sales and stadium attendance.\r\n\r\nTransfers (Orange): 12% – Income generated from player transfers.\r\n\r\nPrize Money (Light Blue): 8% – Earnings from winning or participating in tournaments.\r\n\r\nMerchandise (Green): 8% – Revenue from selling team-branded items such as jerseys, scarves, and other fan gear.\r\n\r\nSponsorship (Yellow): 5% – Revenue from commercial partnerships and sponsors.\r\n\r\n",
                            Solved = false,
                            Title = "Revenue and Fan Age Distribution in International Football",
                            Total = "",
                            UserAnswer = ""
                        },
                        new
                        {
                            Id = 5,
                            EnhancedAnswer = "",
                            Image = "uploads/Test5.png",
                            Question = "2000 – Total Income: $97 billion\r\nRevenue by Industry (in billions):\r\n\r\nSoft Beverages Industry (Blue): 25\r\n\r\nReal Estate Development (Red): 20\r\n\r\nInformation Services (Yellow): 25\r\n\r\nLife Insurance (Green): 12\r\n\r\nSemiconductor Industry (Orange): 15\r\n\r\n2050 (Projected) – Total Income: $196 billion\r\nRevenue by Industry (in billions):\r\n\r\nSoft Beverages Industry (Blue): 25\r\n\r\nReal Estate Development (Red): 25\r\n\r\nInformation Services (Yellow): 10\r\n\r\nLife Insurance (Green): 10\r\n\r\nSemiconductor Industry (Orange): 126",
                            Solved = false,
                            Title = "Revenue from 5 Industries in Togo (2000 vs 2050)",
                            Total = "",
                            UserAnswer = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
